---
name: E2E Tests

on: [workflow_dispatch, pull_request]

jobs:
  test-and-build:
    name: Test+Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build
        run: mvn -DskipTests --quiet --no-transfer-progress verify

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/jenkinsci/tekton-client-plugin:latest

      - name: Install Kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Install Kind
        uses: helm/kind-action@v1.1.0
        with:
          cluster_name: tekton-client-plugin

      - name: Run chart-testing (install)
        run: ct install


            #        run: make install-tekton

            #      - name: Coverage
            #        run: make coverage

            #      - name: Upload Coverage
            #        run: bash <(curl -s https://codecov.io/bash)
